import { Routine } from "./types";

// Helper to get image path - folder names are normalized (no trailing dots)
const getImg = (name: string) => `/images/exercises/${name}/screen.png`;

export const routines: Routine[] = [
  {
    day: 1,
    title: "Día 1: Empuje",
    subtitle: "Pecho y hombros. 6 ejercicios puros, ~30 min.",
    type: "strength",
    duration: "30 MIN",
    difficulty: "Intermedio",
    equipment: "MANCUERNAS",
    coverImage: getImg("dumbbell_flat_bench"),
    exercises: [
      {
        id: "d1-1",
        name: "Press de Banca Plano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description: "Empuje horizontal con mancuernas. Mantén los codos a 45 grados y núcleo estable.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_flat_bench"),
      },
      {
        id: "d1-2",
        name: "Press Militar Sentado",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description: "Press de hombros sentado. Evita arquear la espalda al subir.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("seated_military"),
      },
      {
        id: "d1-3",
        name: "Aperturas en Banco",
        sets: 3,
        reps: "12-15",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Aperturas controladas. Siente el estiramiento en el pecho.",
        tempo: "3 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_flyes"),
      },
      {
        id: "d1-4",
        name: "Elevaciones Laterales",
        sets: 3,
        reps: "12-15",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Eleva los brazos a los lados hasta la altura de los hombros. Controla el descenso.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Principiante",
        image: getImg("lateral_raise"),
      },
      {
        id: "d1-5",
        name: "Flexiones",
        sets: 3,
        reps: "Al fallo",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Remata el pecho con flexiones al fallo. Mantén el cuerpo recto.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Principiante",
        image: getImg("classic_push_ups"),
      },
      {
        id: "d1-6",
        name: "Elevación Frontal",
        sets: 3,
        reps: "10-12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Eleva las mancuernas al frente hasta la altura de los hombros. Controla la bajada.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("front_raise"),
      },
    ],
  },
  {
    day: 2,
    title: "Día 2: Tirón",
    subtitle: "Espalda, bíceps y posterior. 6 ejercicios puros, ~30 min.",
    type: "strength",
    duration: "30 MIN",
    difficulty: "Intermedio",
    equipment: "MANCUERNAS",
    coverImage: getImg("one_arm_dumbbell"),
    exercises: [
      {
        id: "d2-1",
        name: "Remo a una mano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description: "Remo unilateral con mancuerna. Mantén la espalda recta y tira hacia el bolsillo.",
        tempo: "2 - 1 - 2 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("one_arm_dumbbell"),
      },
      {
        id: "d2-2",
        name: "Curl Martillo",
        sets: 3,
        reps: "10-12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Curl con palmas neutras. Trabaja braquial y braquiorradial.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Principiante",
        image: getImg("hammer_curl"),
      },
      {
        id: "d2-3",
        name: "Peso Muerto con Mancuernas",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description: "Peso muerto con piernas semi-rígidas. Espalda recta y caderas hacia atrás.",
        tempo: "3 - 1 - 2 - 0",
        category: "back",
        difficulty: "Avanzado",
        image: getImg("deadlift"),
      },
      {
        id: "d2-4",
        name: "Curl de Bíceps Clásico",
        sets: 3,
        reps: "10-12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Curl con palmas hacia arriba. Control total, no balancees el cuerpo.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Principiante",
        image: getImg("dumbbell_biceps"),
      },
      {
        id: "d2-5",
        name: "Aperturas Inversas",
        sets: 3,
        reps: "12-15",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Inclinado hacia delante, abre los brazos trabajando el deltoides posterior.",
        tempo: "2 - 0 - 2 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("reverse_fly"),
      },
      {
        id: "d2-6",
        name: "Renegade Row",
        sets: 3,
        reps: "12",
        restSeconds: 75,
        equipment: "dumbbells",
        description: "Remo en plancha. Evita rotar las caderas y mantén el núcleo activo.",
        tempo: "2 - 1 - 2 - 0",
        category: "back",
        difficulty: "Avanzado",
        image: getImg("renegade_row"),
      },
    ],
  },
  {
    day: 3,
    title: "Día 3: HIIT",
    subtitle: "Máxima intensidad. Quema calórica extrema y mejora cardiovascular.",
    type: "hiit",
    duration: "30 MIN",
    difficulty: "Cardio HIIT",
    equipment: "MANCUERNAS / PESO CORPORAL",
    coverImage: getImg("dumbbell_thrusters"),
    coverImageBodyweight: getImg("burpees_bodyweight"),
    exercises: [
      {
        id: "d3-a-1",
        name: "Dumbbell Thrusters",
        sets: 4,
        reps: "15",
        restSeconds: 90,
        equipment: "dumbbells",
        description: "Sentadilla con press de hombros. Movimiento fluido y continuo.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("dumbbell_thrusters"),
      },
      {
        id: "d3-a-2",
        name: "Renegade Row",
        sets: 4,
        reps: "12",
        restSeconds: 90,
        equipment: "dumbbells",
        description: "Remo en plancha. Evita rotar las caderas.",
        tempo: "Controlado",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("renegade_row"),
      },
      {
        id: "d3-a-3",
        name: "Swing con Mancuerna",
        sets: 4,
        reps: "20",
        restSeconds: 90,
        equipment: "dumbbells",
        description: "Swing ruso con mancuerna. Impulsa con caderas, no con brazos.",
        tempo: "Explosivo",
        category: "full_body",
        difficulty: "Intermedio",
        image: getImg("dumbbell_swing"),
      },
      {
        id: "d3-a-4",
        name: "Zancadas con Salto",
        sets: 4,
        reps: "30s",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Zancadas alternas con salto. Aterriza suave.",
        tempo: "Rápido",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("jumping_lunges"),
      },
      {
        id: "d3-a-5",
        name: "Devil Press",
        sets: 4,
        reps: "10",
        restSeconds: 90,
        equipment: "dumbbells",
        description: "Burpee con mancuernas + press. Ejercicio compuesto total.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("devil_press"),
      },
      {
        id: "d3-a-6",
        name: "High Knees",
        sets: 4,
        reps: "45s",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Corre en el sitio subiendo las rodillas al pecho. Ritmo máximo.",
        tempo: "Rápido",
        category: "full_body",
        difficulty: "Intermedio",
        image: getImg("high_knees"),
      },
      {
        id: "d3-a-7",
        name: "Plank Jacks",
        sets: 4,
        reps: "30s",
        restSeconds: 45,
        equipment: "bodyweight",
        description: "En posición de plancha, abre y cierra las piernas. Core activo.",
        tempo: "Rápido",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("plank_jack"),
      },
      {
        id: "d3-a-8",
        name: "Tuck Jumps",
        sets: 4,
        reps: "10",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Salto vertical llevando las rodillas al pecho. Aterriza suave.",
        tempo: "Explosivo",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("tuck_jump"),
      },
    ],
    alternativeExercises: [
      {
        id: "d3-b-1",
        name: "Sentadillas con Salto",
        sets: 4,
        reps: "15",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Sentadilla con salto en la subida. Aterriza amortiguando.",
        tempo: "Explosivo",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("jump_squats"),
      },
      {
        id: "d3-b-2",
        name: "Flexiones",
        sets: 4,
        reps: "Al fallo",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Push-ups clásicas. Mantén el cuerpo recto.",
        tempo: "Controlado",
        category: "chest",
        difficulty: "Principiante",
        image: getImg("classic_push_ups"),
      },
      {
        id: "d3-b-3",
        name: "Mountain Climbers",
        sets: 4,
        reps: "45s",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Escaladores. Ritmo rápido manteniendo plancha.",
        tempo: "Rápido",
        category: "full_body",
        difficulty: "Intermedio",
        image: getImg("mountain_climbers"),
      },
      {
        id: "d3-b-4",
        name: "Jumping Jacks",
        sets: 4,
        reps: "60s",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Saltos de tijera. Brazos arriba y abajo coordinados.",
        tempo: "Constante",
        category: "full_body",
        difficulty: "Principiante",
        image: getImg("jumping_jacks"),
      },
      {
        id: "d3-b-5",
        name: "Burpees Clásicos",
        sets: 4,
        reps: "12",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Burpees completos. Pecho al suelo y salto vertical.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("burpees_bodyweight"),
      },
      {
        id: "d3-b-6",
        name: "Sentadilla con Salto",
        sets: 4,
        reps: "15",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Sentadilla profunda con salto explosivo. Aterriza con control.",
        tempo: "Explosivo",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("squat_jump"),
      },
    ],
  },
  {
    day: 4,
    title: "Extra: Libre",
    subtitle: "Ejercicio libre para trabajar lo que tú quieras. Configurable y adaptable.",
    type: "strength",
    duration: "20 MIN",
    difficulty: "Intermedio",
    equipment: "LIBRE",
    coverImage: getImg("free_workout"),
    exercises: [
      {
        id: "ex-1",
        name: "Ejercicio Libre",
        sets: 3,
        reps: "Tu elección",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Elección libre. Elige el movimiento, el peso y las repeticiones según tu objetivo del día.",
        category: "full_body",
        difficulty: "Principiante",
        image: getImg("free_workout"),
      },
    ],
  },
  {
    day: 5,
    title: "Día 5: Full Body",
    subtitle: "Entrenamiento completo de cuerpo entero. Mantiene pierna y remata la semana.",
    type: "strength",
    duration: "45 MIN",
    difficulty: "Avanzado",
    equipment: "MANCUERNAS",
    coverImage: getImg("clean_press"),
    exercises: [
      {
        id: "d5-1",
        name: "Clean & Press",
        sets: 4,
        reps: "10",
        restSeconds: 90,
        equipment: "dumbbells",
        description: "Clean con mancuernas seguido de press militar. Movimiento olímpico adaptado.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("clean_press"),
      },
      {
        id: "d5-2",
        name: "Sentadilla Sumo",
        sets: 4,
        reps: "12",
        restSeconds: 90,
        equipment: "dumbbells",
        description: "Sentadilla con pies abiertos. Trabaja inner thigh y glúteos.",
        tempo: "3 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("sumo_squat"),
      },
      {
        id: "d5-3",
        name: "Remo a una mano",
        sets: 4,
        reps: "10-12",
        restSeconds: 90,
        equipment: "dumbbells",
        description: "Remo unilateral. Espalda recta y tira hacia el bolsillo.",
        tempo: "2 - 1 - 2 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("one_arm_dumbbell"),
      },
      {
        id: "d5-4",
        name: "Push Press",
        sets: 3,
        reps: "12",
        restSeconds: 75,
        equipment: "dumbbells",
        description: "Press con impulso de piernas. Sube explosivo, baja controlado.",
        tempo: "Potente",
        category: "shoulders",
        difficulty: "Avanzado",
        image: getImg("push_press"),
      },
      {
        id: "d5-5",
        name: "Woodchopper",
        sets: 3,
        reps: "12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Giro diagonal de arriba a abajo. Trabaja core y oblicuos.",
        tempo: "2 - 0 - 2 - 0",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("woodchopper"),
      },
      {
        id: "d5-6",
        name: "Man Makers",
        sets: 3,
        reps: "8",
        restSeconds: 90,
        equipment: "dumbbells",
        description: "Burpee + remo unilateral + flexión + press. Ejercicio total completo.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("man_maker"),
      },
      {
        id: "d5-7",
        name: "Elevación de Gemelos",
        sets: 3,
        reps: "20",
        restSeconds: 45,
        equipment: "dumbbells",
        description: "Sube de puntillas. Mantén la contracción arriba un segundo.",
        tempo: "2 - 1 - 2 - 0",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("calf_raise"),
      },
    ],
  },
];

export const warmUpExercises = [
  {
    id: "wu-1",
    name: "Rotación articular",
    sets: 1,
    reps: "10 círculos",
    restSeconds: 60,
    equipment: "bodyweight" as const,
    description: "Tobillos, rodillas, cadera, hombros",
    image: getImg("joint_rotations"),
  },
  {
    id: "wu-2",
    name: "Sentadillas libres",
    sets: 1,
    reps: "15",
    restSeconds: 60,
    equipment: "bodyweight" as const,
    description: "Calentamiento dinámico",
    image: getImg("bodyweight_squats"),
  },
  {
    id: "wu-3",
    name: "Flexiones (pared/banco)",
    sets: 1,
    reps: "10",
    restSeconds: 60,
    equipment: "bodyweight" as const,
    description: "Activación de pecho y tríceps",
    image: getImg("wall_bench_push"),
  },
  {
    id: "wu-4",
    name: "Jumping Jacks",
    sets: 1,
    reps: "30s",
    restSeconds: 60,
    equipment: "bodyweight" as const,
    description: "Elevación de ritmo cardíaco",
    image: getImg("jumping_jacks"),
  },
  {
    id: "wu-5",
    name: "High Knees",
    sets: 1,
    reps: "30s",
    restSeconds: 30,
    equipment: "bodyweight" as const,
    description: "Activación de caderas y ritmo cardíaco",
    image: getImg("high_knees"),
  },
  {
    id: "wu-6",
    name: "Elevación de Piernas",
    sets: 1,
    reps: "10",
    restSeconds: 30,
    equipment: "bodyweight" as const,
    description: "Activación del core",
    image: getImg("leg_raise"),
  },
];
