import { Routine } from "./types";

// Helper to get image path - using simplified names
const getImg = (name: string) => `/images/exercises/${name}/screen.png`;

export const routines: Routine[] = [
  {
    day: 1,
    title: "Día 1: Empuje/Tirón",
    subtitle: "Combinación explosiva de movimientos de tracción y empuje para el tren superior.",
    type: "strength",
    duration: "45 MIN",
    difficulty: "Intermedio",
    equipment: "MANCUERNAS • CABLES",
    coverImage: getImg("dumbbell_flat_bench"),
    exercises: [
      {
        id: "d1-1",
        name: "Press de Banca Plano",
        sets: 3,
        reps: "10-12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Empuje horizontal con mancuernas. Mantén los codos a 45 grados y el núcleo estable.",
        tempo: "2 - 0 - 2 - 0",
        image: getImg("dumbbell_flat_bench"),
      },
      {
        id: "d1-2",
        name: "Remo a una mano",
        sets: 3,
        reps: "10-12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Remo unilateral con mancuerna. Mantén la espalda recta y tira hacia el bolsillo.",
        tempo: "2 - 1 - 2 - 0",
        image: getImg("one_arm_dumbbell"),
      },
      {
        id: "d1-3",
        name: "Press Militar Sentado",
        sets: 3,
        reps: "10",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Press de hombros sentado. Evita arquear la espalda al subir.",
        tempo: "2 - 0 - 2 - 0",
        image: getImg("seated_military"),
      },
      {
        id: "d1-4",
        name: "Curl de Bíceps Clásico",
        sets: 3,
        reps: "12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Curl con palmas hacia arriba. No balancees el cuerpo.",
        tempo: "2 - 0 - 2 - 0",
        image: getImg("dumbbell_biceps"),
      },
      {
        id: "d1-5",
        name: "Aperturas en Banco",
        sets: 3,
        reps: "12-15",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Aperturas controladas. Siente el estiramiento en el pecho.",
        tempo: "3 - 0 - 2 - 0",
        image: getImg("dumbbell_flyes."),
      },
      {
        id: "d1-6",
        name: "Copa de Tríceps",
        sets: 3,
        reps: "12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Extensión de tríceps por encima de la cabeza. Mantén los codos fijos.",
        tempo: "2 - 0 - 2 - 0",
        image: getImg("triceps_overhead"),
      },
      {
        id: "d1-7",
        name: "Curl Martillo",
        sets: 3,
        reps: "12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Curl con palmas neutras. Trabaja braquial y braquiorradial.",
        tempo: "2 - 0 - 2 - 0",
        image: getImg("hammer_curl."),
      },
      {
        id: "d1-8",
        name: "Patada de Tríceps",
        sets: 3,
        reps: "12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Extensión de tríceps a una mano. Mantén el codo pegado al cuerpo.",
        tempo: "2 - 1 - 2 - 0",
        image: getImg("triceps_kickback."),
      },
    ],
  },
  {
    day: 2,
    title: "Día 2: Pierna/Core",
    subtitle: "Cimiento sólido. Trabajo pesado de tren inferior y estabilidad abdominal profunda.",
    type: "strength",
    duration: "50 MIN",
    difficulty: "Avanzado",
    equipment: "MANCUERNAS • PESO CORPORAL",
    coverImage: getImg("goblet_squat."),
    exercises: [
      {
        id: "d2-1",
        name: "Sentadilla Goblet",
        sets: 4,
        reps: "12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Sentadilla con mancuerna al pecho. Mantén la espalda recta.",
        tempo: "3 - 0 - 2 - 0",
        image: getImg("goblet_squat."),
      },
      {
        id: "d2-2",
        name: "Peso Muerto Rumano",
        sets: 4,
        reps: "12-15",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Peso muerto a piernas rígidas. Siente el estiramiento en isquiotibiales.",
        tempo: "3 - 1 - 2 - 0",
        image: getImg("dumbbell_romanian"),
      },
      {
        id: "d2-3",
        name: "Crunch Abdominal",
        sets: 3,
        reps: "20",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Encogimiento abdominal. No tires del cuello.",
        tempo: "2 - 0 - 2 - 0",
        image: getImg("abdominal_crunch."),
      },
      {
        id: "d2-4",
        name: "Zancada Búlgara",
        sets: 3,
        reps: "10",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Zancada con pie trasero elevado. Controla el descenso.",
        tempo: "3 - 0 - 2 - 0",
        image: getImg("bulgarian_split"),
      },
      {
        id: "d2-5",
        name: "Puente de Glúteo",
        sets: 3,
        reps: "15",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Hip thrust. Aprieta glúteos en la parte superior.",
        tempo: "2 - 2 - 2 - 0",
        image: getImg("dumbbell_glute"),
      },
      {
        id: "d2-6",
        name: "Plancha Abdominal",
        sets: 3,
        reps: "45-60s",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Plancha isométrica. Mantén el cuerpo en línea recta.",
        tempo: "Isométrico",
        image: getImg("plank._single"),
      },
      {
        id: "d2-7",
        name: "Step-Up",
        sets: 3,
        reps: "12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Subida a banco. Empuja con el talón del pie de apoyo.",
        tempo: "2 - 0 - 2 - 0",
        image: getImg("dumbbell_step_up."),
      },
    ],
  },
  {
    day: 3,
    title: "Día 3: HIIT",
    subtitle: "Máxima intensidad en corto tiempo. Quema calórica extrema y mejora cardiovascular.",
    type: "hiit",
    duration: "30 MIN",
    difficulty: "Cardio HIIT",
    equipment: "EQUIPAMIENTO",
    coverImage: getImg("dumbbell_thrusters."),
    coverImageBodyweight: getImg("burpees_bodyweight."),
    exercises: [
      {
        id: "d3-a-1",
        name: "Dumbbell Thrusters",
        sets: 4,
        reps: "15",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Sentadilla con press de hombros. Movimiento fluido y continuo.",
        tempo: "Potente",
        image: getImg("dumbbell_thrusters."),
      },
      {
        id: "d3-a-2",
        name: "Renegade Row",
        sets: 4,
        reps: "12",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Remo en plancha. Evita rotar las caderas.",
        tempo: "Controlado",
        image: getImg("renegade_row."),
      },
      {
        id: "d3-a-3",
        name: "Swing con Mancuerna",
        sets: 4,
        reps: "20",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Swing ruso con mancuerna. Impulsa con caderas, no con brazos.",
        tempo: "Explosivo",
        image: getImg("dumbbell_swing."),
      },
      {
        id: "d3-a-4",
        name: "Zancadas con Salto",
        sets: 4,
        reps: "30s",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Zancadas alternas con salto. Aterriza suave.",
        tempo: "Rápido",
        image: getImg("jumping_lunges."),
      },
      {
        id: "d3-a-5",
        name: "Devil Press",
        sets: 4,
        reps: "10",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Burpee con mancuernas + press. Ejercicio compuesto total.",
        tempo: "Potente",
        image: getImg("devil_press."),
      },
    ],
    alternativeExercises: [
      {
        id: "d3-b-1",
        name: "Sentadillas con Salto",
        sets: 4,
        reps: "15",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Sentadilla con salto en la subida. Aterriza amortiguando.",
        tempo: "Explosivo",
        image: getImg("jump_squats."),
      },
      {
        id: "d3-b-2",
        name: "Flexiones",
        sets: 4,
        reps: "Al fallo",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Push-ups clásicas. Mantén el cuerpo recto.",
        tempo: "Controlado",
        image: getImg("classic_push_ups."),
      },
      {
        id: "d3-b-3",
        name: "Mountain Climbers",
        sets: 4,
        reps: "45s",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Escaladores. Ritmo rápido manteniendo plancha.",
        tempo: "Rápido",
        image: getImg("mountain_climbers."),
      },
      {
        id: "d3-b-4",
        name: "Jumping Jacks",
        sets: 4,
        reps: "60s",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Saltos de tijera. Brazos arriba y abajo coordinados.",
        tempo: "Constante",
        image: getImg("jumping_jacks."),
      },
      {
        id: "d3-b-5",
        name: "Burpees Clásicos",
        sets: 4,
        reps: "12",
        restSeconds: 60,
        equipment: "bodyweight",
        description: "Burpees completos. Pecho al suelo y salto vertical.",
        tempo: "Potente",
        image: getImg("burpees_bodyweight."),
      },
    ],
  },
  {
    day: 4,
    title: "Extra: Libre",
    subtitle: "Ejercicio libre para trabajar lo que tú quieras. Configurable y adaptable.",
    type: "strength",
    duration: "20 MIN",
    difficulty: "Intermedio",
    equipment: "LIBRE",
    coverImage: getImg("free_workout"),
    exercises: [
      {
        id: "ex-1",
        name: "Ejercicio Libre",
        sets: 3,
        reps: "Tu elección",
        restSeconds: 60,
        equipment: "dumbbells",
        description: "Elección libre. Elige el movimiento, el peso y las repeticiones según tu objetivo del día.",
        image: getImg("free_workout"),
      },
    ],
  },
];

export const warmUpExercises = [
  {
    id: "wu-1",
    name: "Rotación articular",
    sets: 1,
    reps: "10 círculos",
    restSeconds: 60,
    equipment: "bodyweight" as const,
    description: "Tobillos, rodillas, cadera, hombros",
    image: getImg("joint_rotations."),
  },
  {
    id: "wu-2",
    name: "Sentadillas libres",
    sets: 1,
    reps: "15",
    restSeconds: 60,
    equipment: "bodyweight" as const,
    description: "Calentamiento dinámico",
    image: getImg("bodyweight_squats."),
  },
  {
    id: "wu-3",
    name: "Flexiones (pared/banco)",
    sets: 1,
    reps: "10",
    restSeconds: 60,
    equipment: "bodyweight" as const,
    description: "Activación de pecho y tríceps",
    image: getImg("wall_bench_push"),
  },
  {
    id: "wu-4",
    name: "Jumping Jacks",
    sets: 1,
    reps: "30s",
    restSeconds: 60,
    equipment: "bodyweight" as const,
    description: "Elevación de ritmo cardíaco",
    image: getImg("jumping_jacks."),
  },
];
