import { Plan, Routine, Exercise } from "./types";

// Helper to get image path - folder names are normalized (no trailing dots)
const getImg = (name: string, ext = "webp") => `/images/exercises/${name}/screen.${ext}`;

// Unique exercise catalog built from all routines (including alternatives)
const allExerciseMap = new Map<string, Exercise>();
const addExercise = (ex: Exercise) => {
  if (!allExerciseMap.has(ex.id)) allExerciseMap.set(ex.id, ex);
};

export const getAllExercises = (): Exercise[] =>
  Array.from(allExerciseMap.values());
export const getExerciseById = (id: string): Exercise | undefined =>
  allExerciseMap.get(id);

export const routines: Routine[] = [
  // ==========================================
  // DÍA 1: EMPUJE (Pecho, Hombros y Tríceps)
  // ==========================================
  {
    day: 1,
    title: "Día 1: Empuje",
    subtitle: "Pecho, hombros y tríceps. 7 ejercicios de fuerza, ~35 min.",
    type: "strength",
    duration: "35 MIN",
    difficulty: "Intermedio",
    equipment: "MANCUERNAS",
    categoryTag: "fuerza",
    coverImage: getImg("dumbbell_flat_bench"),
    exercises: [
      {
        id: "d1-1",
        name: "Press de Banca Plano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Empuje horizontal con mancuernas. Mantén los codos a 45 grados y núcleo estable.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_flat_bench"),
      },
      {
        id: "d1-2",
        name: "Press Militar Sentado",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Press de hombros vertical sentado. Evita arquear la zona lumbar.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("seated_military"),
      },
      {
        id: "d1-3",
        name: "Extensión de Tríceps sobre Cabeza",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Sujeta la mancuerna con ambas manos y extiende verticalmente. Controla la bajada.",
        tempo: "2 - 0 - 2 - 1",
        category: "triceps",
        difficulty: "Intermedio",
        image: getImg("overhead_extension"),
      },
      {
        id: "d1-4",
        name: "Aperturas en Banco",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Aperturas con codos ligeramente flexionados. Siente el estiramiento pectoral.",
        tempo: "3 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_flyes"),
      },
      {
        id: "d1-5",
        name: "Elevaciones Laterales",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Eleva los brazos lateralmente hasta la altura de los hombros. Controla la bajada.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Principiante",
        image: getImg("lateral_raise"),
      },
      {
        id: "d1-6",
        name: "Patada de Tríceps",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Torso inclinado, codo pegado al costado y extiende hacia atrás hasta el bloqueo.",
        tempo: "2 - 0 - 2 - 1",
        category: "triceps",
        difficulty: "Intermedio",
        image: getImg("triceps_kickback"),
      },
      {
        id: "d1-7",
        name: "Flexiones al Fallo",
        sets: 3,
        reps: "Al fallo",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Remate final de pecho y tríceps con flexiones estrictas. Mantén el cuerpo en bloque.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Principiante",
        image: getImg("classic_push_ups"),
      },
    ],
  },

  // ==========================================
  // DÍA 2: TIRÓN + PIERNA
  // ==========================================
  {
    day: 2,
    title: "Día 2: Tirón + Pierna",
    subtitle: "Espalda, bíceps, pierna y burpees. 7 ejercicios, ~35 min.",
    type: "strength",
    duration: "35 MIN",
    difficulty: "Intermedio",
    equipment: "MANCUERNAS",
    categoryTag: "fuerza",
    coverImage: getImg("deadlift"),
    exercises: [
      {
        id: "d2-1",
        name: "Peso Muerto con Mancuernas",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Piernas semi-rígidas, espalda neutra, caderas hacia atrás sintiendo los isquios.",
        tempo: "3 - 1 - 2 - 0",
        category: "back",
        difficulty: "Avanzado",
        image: getImg("deadlift"),
      },
      {
        id: "d2-2",
        name: "Curl de Bíceps Clásico",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Curl con palmas en supinación. Control estricto, sin balanceo de cadera.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Principiante",
        image: getImg("dumbbell_biceps"),
      },
      {
        id: "d2-3",
        name: "Sentadilla Goblet",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Mancuerna pegada al pecho y sentadilla profunda con rodillas hacia afuera.",
        tempo: "2 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("goblet_squat"),
      },
      {
        id: "d2-4",
        name: "Remo a una mano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Remo unilateral apoyado en banco. Tira hacia la cadera contrayendo el dorsal.",
        tempo: "2 - 1 - 2 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("one_arm_dumbbell"),
      },
      {
        id: "d2-5",
        name: "Curl Martillo",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Palmas enfrentadas (agarre neutro). Enfoque en braquial anterior y antebrazos.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Principiante",
        image: getImg("hammer_curl"),
      },
      {
        id: "d2-6",
        name: "Zancadas Caminando",
        sets: 3,
        reps: "10-12 por pierna",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Pasos largos alternados, torso recto y rodilla trasera casi tocando el suelo.",
        tempo: "2 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("walking_lunges"),
      },
      {
        id: "d2-7",
        name: "Burpees al Fallo",
        sets: 3,
        reps: "Al fallo",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Remate cardiovascular total: pecho al suelo, salto explosivo y aplauso arriba.",
        tempo: "1 - 0 - 1 - 0",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("burpees"),
      },
    ],
  },

  // ==========================================
  // DÍA 3: FULL BODY COMBO (DÍA 1 + DÍA 2)
  // ==========================================
  {
    day: 3,
    title: "Día 3: Full Body Combo (Día 1 + 2)",
    subtitle:
      "La fusión definitiva de Empuje, Tirón y Pierna. 10 ejercicios completos, ~45 min.",
    type: "strength",
    duration: "45 MIN",
    difficulty: "Avanzado",
    equipment: "MANCUERNAS",
    categoryTag: "full_body",
    coverImage: getImg("dumbbell_flat_bench"),
    exercises: [
      {
        id: "d3c-1",
        name: "Press de Banca Plano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Empuje pectoral principal con mancuernas. Codos a 45 grados y control constante.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_flat_bench"),
      },
      {
        id: "d3c-2",
        name: "Remo a una mano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Tirón horizontal unilateral. Tira hacia el bolsillo activando todo el dorsal.",
        tempo: "2 - 1 - 2 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("one_arm_dumbbell"),
      },
      {
        id: "d3c-3",
        name: "Sentadilla Goblet",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Sentadilla profunda con mancuerna al pecho. Máxima activación de cuádriceps y glúteos.",
        tempo: "2 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("goblet_squat"),
      },
      {
        id: "d3c-4",
        name: "Peso Muerto con Mancuernas",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Bisagra de cadera con espalda recta. Enfoque en cadena posterior e isquiotibiales.",
        tempo: "3 - 1 - 2 - 0",
        category: "back",
        difficulty: "Avanzado",
        image: getImg("deadlift"),
      },
      {
        id: "d3c-5",
        name: "Press Militar Sentado",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Empuje vertical de hombros. Espalda apoyada y control en la bajada.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("seated_military"),
      },
      {
        id: "d3c-6",
        name: "Curl de Bíceps Clásico",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Aislamiento de bíceps con giro de muñeca arriba para máxima contracción.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Principiante",
        image: getImg("dumbbell_biceps"),
      },
      {
        id: "d3c-7",
        name: "Extensión de Tríceps sobre Cabeza",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Extensión vertical a dos manos. Codos estables y recorrido amplio.",
        tempo: "2 - 0 - 2 - 1",
        category: "triceps",
        difficulty: "Intermedio",
        image: getImg("overhead_extension"),
      },
      {
        id: "d3c-8",
        name: "Elevaciones Laterales",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Aislamiento del deltoides lateral. Eleva con codos ligeramente flexionados.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Principiante",
        image: getImg("lateral_raise"),
      },
      {
        id: "d3c-9",
        name: "Zancadas Caminando",
        sets: 3,
        reps: "10-12 por pierna",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Zancadas dinámicas para terminar de fatigar piernas y glúteos.",
        tempo: "2 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("walking_lunges"),
      },
      {
        id: "d3c-10",
        name: "Remate Final: Burpees o Flexiones",
        sets: 3,
        reps: "Al fallo",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Explosión total para terminar la sesión full body al límite de energía.",
        tempo: "1 - 0 - 1 - 0",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("burpees"),
      },
    ],
  },

  // ==========================================
  // DÍA 4: HIIT QUEMA GRASA & ACONDICIONAMIENTO
  // ==========================================
  {
    day: 4,
    title: "Día 4: HIIT Full Body",
    subtitle:
      "Circuito quemagrasa extremo con mancuernas. 40s trabajo / 20s descanso. ~30 min.",
    type: "hiit",
    duration: "30 MIN",
    difficulty: "Cardio HIIT",
    equipment: "MANCUERNAS / PESO CORPORAL",
    categoryTag: "hiit",
    coverImage: getImg("dumbbell_thrusters", "jpg"),
    coverImageBodyweight: getImg("burpees", "jpg"),
    exercises: [
      {
        id: "d4-a-1",
        name: "Sentadilla Goblet",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description: "Sentadilla profunda con mancuerna al pecho.",
        tempo: "Fluido",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("goblet_squat"),
      },
      {
        id: "d4-a-2",
        name: "Dumbbell Floor Press",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description: "Press de pecho desde el suelo con mancuernas. Controla la bajada hasta que los tríceps toquen el suelo.",
        tempo: "Controlado",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_floor_press", "jpg"),
      },
      {
        id: "d4-a-3",
        name: "Devil Press",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description: "Combinación explosiva de burpee y snatch con mancuernas.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("devil_press", "jpg"),
      },
      {
        id: "d4-a-4",
        name: "Remo a una Mano",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description: "Tirón horizontal. Alterna de brazo cada 20 segundos.",
        tempo: "Fluido",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("single_arm_row", "jpg"),
      },
      {
        id: "d4-a-5",
        name: "Press Militar de Hombros",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description: "Press vertical de pie con mancuernas. Core activo y espalda recta.",
        tempo: "Controlado",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("seated_military"),
      },
      {
        id: "d4-a-6",
        name: "Dumbbell Thrusters",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description: "Sentadilla y press de hombros simultáneo y explosivo con mancuernas.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("dumbbell_thrusters", "jpg"),
      },
      {
        id: "d4-a-7",
        name: "Peso Muerto Rumano",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description: "Enfoque en isquios y glúteos con mancuernas. Espalda neutra.",
        tempo: "Fluido",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("deadlift"),
      },
      {
        id: "d4-a-8",
        name: "Zancadas con Mancuernas",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description: "Zancadas dinámicas sujetando mancuernas a los lados.",
        tempo: "Controlado",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("walking_lunges"),
      },
      {
        id: "d4-a-9",
        name: "Renegade Row con Mancuernas",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description: "En posición de plancha sobre mancuernas, remo alternado potente.",
        tempo: "Controlado",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("renegade_row", "jpg"),
      },
    ],
    alternativeExercises: [
      {
        id: "d4-b-1",
        name: "Sentadillas con Salto",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Sentadilla libre y salto vertical amortiguando la caída.",
        tempo: "Explosivo",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("jump_squats"),
      },
      {
        id: "d4-b-2",
        name: "Flexiones Explosivas",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Push-ups rítmicos o explosivos con palmada.",
        tempo: "Potente",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("classic_push_ups"),
      },
      {
        id: "d4-b-3",
        name: "Mountain Climbers",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Escaladores rápidos.",
        tempo: "Rápido",
        category: "full_body",
        difficulty: "Intermedio",
        image: getImg("mountain_climbers", "jpg"),
      },
      {
        id: "d4-b-4",
        name: "Plank Jacks",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Abre y cierra piernas en plancha.",
        tempo: "Rápido",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("plank_jack"),
      },
      {
        id: "d4-b-5",
        name: "Pike Push-ups",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Flexiones en forma de V invertida para hombros.",
        tempo: "Controlado",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("wall_bench_push"),
      },
      {
        id: "d4-b-6",
        name: "Burpees Clásicos",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Ritmo constante y explosivo.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("burpees", "jpg"),
      },
      {
        id: "d4-b-7",
        name: "Puente de Glúteo",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Tumbado boca arriba, eleva caderas rápido y aprieta glúteo arriba.",
        tempo: "Fluido",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("dumbbell_glute"),
      },
      {
        id: "d4-b-8",
        name: "Zancadas con Salto",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Cambia de pierna en el aire.",
        tempo: "Explosivo",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("jumping_lunges", "jpg"),
      },
      {
        id: "d4-b-9",
        name: "High Knees",
        sets: 3,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Frecuencia cardíaca máxima al final del circuito.",
        tempo: "Rápido",
        category: "full_body",
        difficulty: "Principiante",
        image: getImg("high_knees", "jpg"),
      },
    ],
  },

  // ==========================================
  // DÍA 5: TORSO POWER (Tren Superior Completo)
  // ==========================================
  {
    day: 5,
    title: "Día 5: Torso Power",
    subtitle:
      "Pecho, espalda, hombros y brazos. Densidad y fuerza de tren superior. 7 ejercicios, ~35 min.",
    type: "strength",
    duration: "35 MIN",
    difficulty: "Avanzado",
    equipment: "MANCUERNAS",
    categoryTag: "fuerza",
    coverImage: getImg("one_arm_dumbbell"),
    exercises: [
      {
        id: "d5-1",
        name: "Press de Banca Plano",
        sets: 4,
        reps: "8-10",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Serie pesada de empuje pectoral. Máxima estabilidad en escápulas.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Avanzado",
        image: getImg("dumbbell_flat_bench"),
      },
      {
        id: "d5-2",
        name: "Remo a una mano",
        sets: 4,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Remo unilateral pesado. Tira hacia la cresta ilíaca contrayendo dorsal.",
        tempo: "2 - 1 - 2 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("one_arm_dumbbell"),
      },
      {
        id: "d5-3",
        name: "Aperturas en Banco",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Aperturas profundas para aislar y estirar las fibras pectorales.",
        tempo: "3 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_flyes"),
      },
      {
        id: "d5-4",
        name: "Elevaciones Laterales",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Deltoides lateral para amplitud de torso. Descenso en 2 segundos.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Principiante",
        image: getImg("lateral_raise"),
      },
      {
        id: "d5-5",
        name: "Curl Martillo",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Bíceps y braquiorradial. Codos pegados y tensión continua.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Principiante",
        image: getImg("hammer_curl"),
      },
      {
        id: "d5-6",
        name: "Fondos en Banco",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Fondos apoyado en banco para tríceps y porción anterior del deltoides.",
        tempo: "2 - 0 - 2 - 0",
        category: "triceps",
        difficulty: "Principiante",
        image: getImg("wall_bench_push"),
      },
      {
        id: "d5-7",
        name: "Plancha Activa",
        sets: 3,
        reps: "45s",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Bloqueo de core frontal y glúteos para estabilidad espinal.",
        tempo: "Estático",
        category: "core",
        difficulty: "Principiante",
        image: getImg("plank_single"),
      },
    ],
  },

  // ==========================================
  // DÍA 6: PIERNA & GLÚTEO ESCULPIDO
  // ==========================================
  {
    day: 6,
    title: "Día 6: Pierna & Glúteo",
    subtitle:
      "Fuerza de tren inferior, glúteos y estabilidad central. 6 ejercicios, ~32 min.",
    type: "strength",
    duration: "32 MIN",
    difficulty: "Intermedio",
    equipment: "MANCUERNAS",
    categoryTag: "fuerza",
    coverImage: getImg("bulgarian_split", "jpg"),
    exercises: [
      {
        id: "d6-1",
        name: "Sentadilla Búlgara",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Sentadilla unilateral con pie trasero elevado en banco. Enfoque en glúteo y cuádriceps.",
        tempo: "3 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("bulgarian_split", "jpg"),
      },
      {
        id: "d6-2",
        name: "Peso Muerto Sumo",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Posición ancha de piernas, caderas atrás y espalda neutra. Aductores y cadena posterior.",
        tempo: "3 - 1 - 2 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("deadlift"),
      },
      {
        id: "d6-3",
        name: "Sentadilla Goblet Profunda",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Sentadilla profunda con peso al pecho buscando la máxima flexión de rodilla.",
        tempo: "2 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("goblet_squat"),
      },
      {
        id: "d6-4",
        name: "Hip Thrust en Banco",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Mancuerna sobre la cadera, eleva contrayendo glúteos 1 segundo arriba.",
        tempo: "2 - 1 - 2 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("dumbbell_glute"),
      },
      {
        id: "d6-5",
        name: "Zancadas Caminando con Mancuerna",
        sets: 3,
        reps: "12 por pierna",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Zancadas con mancuernas en mano para resistencia y equilibrio dinámico.",
        tempo: "2 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("dumbbell_step_up"),
      },
      {
        id: "d6-6",
        name: "Abdominales Bicicleta",
        sets: 3,
        reps: "25",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Giro de torso coordinado codo-rodilla contralateral para oblicuos y recto abdominal.",
        tempo: "2 - 0 - 2 - 0",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("abdominal_crunch", "jpg"),
      },
    ],
  },

  // ==========================================
  // DÍA 7: BRAZOS & HOMBROS TITAN (3D)
  // ==========================================
  {
    day: 7,
    title: "Día 7: Brazos & Hombros 3D",
    subtitle:
      "Bíceps, tríceps y deltoides en superseries de hipertrofia. 7 ejercicios, ~30 min.",
    type: "strength",
    duration: "30 MIN",
    difficulty: "Intermedio",
    equipment: "MANCUERNAS",
    categoryTag: "fuerza",
    coverImage: getImg("dumbbell_biceps"),
    exercises: [
      {
        id: "d7-1",
        name: "Curl de Bíceps Clásico",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Supinación completa al subir. Codos estables y recorrido amplio.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Principiante",
        image: getImg("dumbbell_biceps"),
      },
      {
        id: "d7-2",
        name: "Extensión de Tríceps sobre Cabeza",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Extensión vertical a dos manos estirando la cabeza larga del tríceps.",
        tempo: "2 - 0 - 2 - 1",
        category: "triceps",
        difficulty: "Intermedio",
        image: getImg("overhead_extension"),
      },
      {
        id: "d7-3",
        name: "Curl Martillo",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Agarre neutro para enfatizar braquial y grosor de brazo.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Principiante",
        image: getImg("hammer_curl"),
      },
      {
        id: "d7-4",
        name: "Patada de Tríceps",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Extensión hacia atrás con parada isométrica de 1 segundo en el bloqueo.",
        tempo: "2 - 0 - 2 - 1",
        category: "triceps",
        difficulty: "Intermedio",
        image: getImg("triceps_kickback"),
      },
      {
        id: "d7-5",
        name: "Elevaciones Laterales",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Elevaciones estrictas sin impulso. Cabeza lateral del deltoides.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Principiante",
        image: getImg("lateral_raise"),
      },
      {
        id: "d7-6",
        name: "Pájaro / Deltoides Posterior",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Torso inclinado, eleva los brazos lateralmente para deltoides posterior y trapecio.",
        tempo: "2 - 1 - 2 - 0",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("reverse_fly"),
      },
      {
        id: "d7-7",
        name: "Fondos en Banco",
        sets: 3,
        reps: "Al fallo",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Remate de tríceps con el peso corporal hasta agotar las fibras.",
        tempo: "2 - 0 - 2 - 0",
        category: "triceps",
        difficulty: "Principiante",
        image: getImg("wall_bench_push"),
      },
    ],
  },

  // ==========================================
  // DÍA 8: FULL BODY EXPRESS (20-25 MIN)
  // ==========================================
  {
    day: 8,
    title: "Día 8: Full Body Express",
    subtitle:
      "6 ejercicios multiarticulares de máxima eficiencia cuando tienes poco tiempo. ~22 min.",
    type: "strength",
    duration: "22 MIN",
    difficulty: "Intermedio",
    equipment: "MANCUERNAS / PESO CORPORAL",
    categoryTag: "full_body",
    coverImage: getImg("dumbbell_thrusters"),
    exercises: [
      {
        id: "d8-1",
        name: "Dumbbell Thrusters",
        sets: 3,
        reps: "12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Sentadilla y press de hombros fluido en un solo movimiento coordinado.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("dumbbell_thrusters"),
      },
      {
        id: "d8-2",
        name: "Remo a una Mano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description: "Remo unilateral con mancuerna para espalda media y dorsales.",
        tempo: "2 - 1 - 2 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("one_arm_dumbbell"),
      },
      {
        id: "d8-3",
        name: "Sentadilla Goblet",
        sets: 3,
        reps: "12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Sentadilla profunda con mancuerna al pecho. Piernas y glúteos.",
        tempo: "2 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("goblet_squat"),
      },
      {
        id: "d8-4",
        name: "Press de Banca Plano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Empuje de pecho con mancuernas para fuerza de torso.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_flat_bench"),
      },
      {
        id: "d8-5",
        name: "Peso Muerto con Mancuernas",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description: "Cadena posterior y zona lumbar con mancuernas.",
        tempo: "3 - 1 - 2 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("deadlift"),
      },
      {
        id: "d8-6",
        name: "Curl de Bíceps",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description: "Aislamiento de brazos y bíceps con mancuernas.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Principiante",
        image: getImg("dumbbell_biceps"),
      },
    ],
    alternativeExercises: [
      {
        id: "d8-b-1",
        name: "Flexiones Clásicas",
        sets: 3,
        reps: "15",
        restSeconds: 75,
        equipment: "bodyweight",
        description: "Empuje pectoral estricto con el propio peso corporal.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Principiante",
        image: getImg("classic_push_ups"),
      },
      {
        id: "d8-b-2",
        name: "Sentadillas Libres con Salto",
        sets: 3,
        reps: "15",
        restSeconds: 75,
        equipment: "bodyweight",
        description: "Sentadillas profundas y dinámicas para cuádriceps y glúteos.",
        tempo: "Explosivo",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("jump_squats"),
      },
      {
        id: "d8-b-3",
        name: "Zancadas Caminando",
        sets: 3,
        reps: "12 por pierna",
        restSeconds: 75,
        equipment: "bodyweight",
        description: "Pasos largos y control unilateral de piernas.",
        tempo: "2 - 0 - 2 - 0",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("walking_lunges"),
      },
      {
        id: "d8-b-4",
        name: "Flexiones Inclinadas en Banco",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "bodyweight",
        description: "Apoyo en banco o superficie para remate pectoral y tríceps.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Principiante",
        image: getImg("wall_bench_push"),
      },
      {
        id: "d8-b-5",
        name: "Mountain Climbers",
        sets: 3,
        reps: "45s",
        restSeconds: 75,
        equipment: "bodyweight",
        description: "Escaladores dinámicos para core y resistencia metabólica.",
        tempo: "Rápido",
        category: "core",
        difficulty: "Principiante",
        image: getImg("mountain_climbers", "jpg"),
      },
      {
        id: "d8-b-6",
        name: "Plancha Isométrica",
        sets: 3,
        reps: "45s",
        restSeconds: 75,
        equipment: "bodyweight",
        description: "Bloqueo total de abdomen y lumbares sobre antebrazos.",
        tempo: "Estático",
        category: "core",
        difficulty: "Principiante",
        image: getImg("plank_single"),
      },
    ],
  },

  // ==========================================
  // DÍA 9: SUPER HIIT & TABATA
  // ==========================================
  {
    day: 9,
    title: "Día 9: Super HIIT & Tabata",
    subtitle:
      "6 ejercicios a intervalos explosivos (40s trabajo / 20s descanso). ~20 min.",
    type: "hiit",
    duration: "20 MIN",
    difficulty: "Cardio HIIT",
    equipment: "MANCUERNAS / PESO CORPORAL",
    categoryTag: "hiit",
    coverImage: getImg("devil_press", "jpg"),
    coverImageBodyweight: getImg("burpees", "jpg"),
    exercises: [
      {
        id: "d9-1",
        name: "Devil Press",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description:
          "Combinación explosiva de burpee y snatch con mancuernas.",
        tempo: "Potente",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("devil_press", "jpg"),
      },
      {
        id: "d9-2",
        name: "Renegade Row",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description:
          "En plancha, remo alterno con mancuernas. Mantén la cadera estable.",
        tempo: "Controlado",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("renegade_row", "jpg"),
      },
      {
        id: "d9-3",
        name: "Dumbbell Thrusters",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description:
          "Sentadilla y press vertical fluido. Un solo movimiento constante.",
        tempo: "Explosivo",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("dumbbell_thrusters", "jpg"),
      },
      {
        id: "d9-4",
        name: "Dumbbell Floor Press",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description:
          "Press de pecho en suelo a ritmo intenso con mancuernas.",
        tempo: "Controlado",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_floor_press", "jpg"),
      },
      {
        id: "d9-5",
        name: "Peso Muerto Rumano",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description:
          "Bisagra de cadera con mancuernas para potencia de cadena posterior.",
        tempo: "Fluido",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("deadlift"),
      },
      {
        id: "d9-6",
        name: "Sentadilla Goblet",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "dumbbells",
        description:
          "Sentadilla profunda sujetando mancuerna al pecho con ritmo continuo.",
        tempo: "Fluido",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("goblet_squat"),
      },
    ],
    alternativeExercises: [
      {
        id: "d9-b-1",
        name: "Burpees Clásicos",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Ritmo constante y pecho al suelo.",
        tempo: "Rápido",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("burpees", "jpg"),
      },
      {
        id: "d9-b-2",
        name: "Mountain Climbers",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Escaladores rápidos al sprint.",
        tempo: "Rápido",
        category: "full_body",
        difficulty: "Intermedio",
        image: getImg("mountain_climbers", "jpg"),
      },
      {
        id: "d9-b-3",
        name: "Sentadillas con Salto",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Saltos verticales de sentadilla amortiguando bien.",
        tempo: "Explosivo",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("jump_squats"),
      },
      {
        id: "d9-b-4",
        name: "High Knees",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Frecuencia rápida de rodillas arriba.",
        tempo: "Rápido",
        category: "full_body",
        difficulty: "Intermedio",
        image: getImg("high_knees", "jpg"),
      },
      {
        id: "d9-b-5",
        name: "Plank Jacks",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Core y glúteos en tensión abriendo y cerrando pies.",
        tempo: "Rápido",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("plank_jack"),
      },
      {
        id: "d9-b-6",
        name: "Jumping Jacks",
        sets: 4,
        reps: "40s",
        restSeconds: 20,
        equipment: "bodyweight",
        description: "Remate cardiovascular total con brazos y piernas.",
        tempo: "Rápido",
        category: "full_body",
        difficulty: "Principiante",
        image: getImg("jumping_jacks"),
      },
    ],
  },

  // ==========================================
  // DÍA 10: MOVILIDAD, CORE & RECUPERACIÓN
  // ==========================================
  {
    day: 10,
    title: "Día 10: Movilidad & Recuperación",
    subtitle:
      "Aperturas articulares, descompresión espinal, activación de core y respiración. ~20 min.",
    type: "strength",
    duration: "20 MIN",
    difficulty: "Principiante",
    equipment: "PESO CORPORAL / LIBRE",
    categoryTag: "movilidad",
    coverImage: getImg("joint_rotations"),
    exercises: [
      {
        id: "d10-1",
        name: "Rotaciones Articulares Dinámicas",
        sets: 2,
        reps: "10 por lado",
        restSeconds: 30,
        equipment: "bodyweight",
        description:
          "Círculos controlados de hombros, cadera y tobillos para lubricación articular.",
        tempo: "Lento",
        category: "full_body",
        difficulty: "Principiante",
        image: getImg("joint_rotations"),
      },
      {
        id: "d10-2",
        name: "Sentadilla Profunda de Movilidad",
        sets: 2,
        reps: "15",
        restSeconds: 30,
        equipment: "bodyweight",
        description:
          "Sentadilla libre manteniendo el fondo 2 segundos para apertura de cadera y tobillo.",
        tempo: "Lento",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("bodyweight_squats", "jpg"),
      },
      {
        id: "d10-3",
        name: "Plancha Frontal Activa",
        sets: 2,
        reps: "45s",
        restSeconds: 30,
        equipment: "bodyweight",
        description:
          "Activación isométrica de transverso abdominal y glúteos con respiración fluida.",
        tempo: "Estático",
        category: "core",
        difficulty: "Principiante",
        image: getImg("plank_single"),
      },
      {
        id: "d10-4",
        name: "Apertura Torácica y Romboides",
        sets: 2,
        reps: "12",
        restSeconds: 30,
        equipment: "bodyweight",
        description:
          "En suelo o cuadrupedia, apertura torácica para movilidad de columna y espalda alta.",
        tempo: "2 - 1 - 2 - 0",
        category: "back",
        difficulty: "Principiante",
        image: getImg("reverse_fly"),
      },
      {
        id: "d10-5",
        name: "Wall Sit Isométrico",
        sets: 2,
        reps: "45s",
        restSeconds: 30,
        equipment: "bodyweight",
        description:
          "Sentadilla isométrica apoyada en pared. Muslos paralelos y respiración tranquila.",
        tempo: "Estático",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("wall_sit"),
      },
      {
        id: "d10-6",
        name: "Elevación de Piernas Controlada",
        sets: 2,
        reps: "12",
        restSeconds: 30,
        equipment: "bodyweight",
        description:
          "Tumbado boca arriba, sube y baja piernas sin despegar la zona lumbar del suelo.",
        tempo: "3 - 0 - 2 - 0",
        category: "core",
        difficulty: "Principiante",
        image: getImg("leg_raise"),
      },
      {
        id: "d10-7",
        name: "Respiración Diafragmática y Relajación",
        sets: 2,
        reps: "60s",
        restSeconds: 0,
        equipment: "bodyweight",
        description:
          "Inhalaciones profundas de 4 segundos y exhalaciones lentas para bajar el sistema nervioso.",
        tempo: "Lento",
        category: "core",
        difficulty: "Principiante",
        image: getImg("free_workout"),
      },
    ],
  },

  // ==========================================
  // DÍA 11 / EXTRA: ENTRENAMIENTO LIBRE
  // ==========================================
  {
    day: 11,
    title: "Extra: Entrenamiento Libre",
    subtitle:
      "Catálogo completo de ejercicios libres. Elige entre mancuernas o peso corporal para tu sesión personalizada.",
    type: "strength",
    duration: "LIBRE",
    difficulty: "Intermedio",
    equipment: "MANCUERNAS / PESO CORPORAL",
    categoryTag: "personalizado",
    coverImage: getImg("free_workout"),
    exercises: [
      {
        id: "d11-db-1",
        name: "Press de Banca Plano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Empuje horizontal con mancuernas. Mantén los codos a 45 grados y núcleo estable.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_flat_bench"),
      },
      {
        id: "d11-db-2",
        name: "Aperturas en Banco",
        sets: 3,
        reps: "12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Aperturas con mancuernas manteniendo una ligera flexión de codos para aislar el pectoral.",
        tempo: "3 - 0 - 1 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_flyes"),
      },
      {
        id: "d11-db-3",
        name: "Dumbbell Floor Press",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Press en el suelo con mancuernas. Pausa de 1 segundo al tocar el suelo con los tríceps.",
        tempo: "2 - 1 - 1 - 0",
        category: "chest",
        difficulty: "Intermedio",
        image: getImg("dumbbell_floor_press"),
      },
      {
        id: "d11-db-4",
        name: "Remo a una Mano",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Tracción unilateral apoyado en banco. Lleva la mancuerna hacia la cadera apretando el dorsal.",
        tempo: "2 - 1 - 2 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("one_arm_dumbbell"),
      },
      {
        id: "d11-db-5",
        name: "Peso Muerto con Mancuernas",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Bisagra de cadera con mancuernas pegadas a las piernas. Espalda neutra y activación de isquios.",
        tempo: "3 - 0 - 1 - 0",
        category: "back",
        difficulty: "Intermedio",
        image: getImg("deadlift"),
      },
      {
        id: "d11-db-6",
        name: "Renegade Row con Mancuernas",
        sets: 3,
        reps: "10 por lado",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "En posición de plancha sobre mancuernas, rema alternando brazos sin rotar la cadera.",
        tempo: "2 - 1 - 1 - 0",
        category: "back",
        difficulty: "Avanzado",
        image: getImg("renegade_row"),
      },
      {
        id: "d11-db-7",
        name: "Press Militar Sentado",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Press de hombros vertical con mancuernas. Codos ligeramente adelantados.",
        tempo: "2 - 0 - 2 - 0",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("seated_military"),
      },
      {
        id: "d11-db-8",
        name: "Elevaciones Laterales",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Abducción de hombros con mancuernas. Eleva hasta la horizontal con control.",
        tempo: "2 - 1 - 1 - 0",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("lateral_raise"),
      },
      {
        id: "d11-db-9",
        name: "Pájaro / Deltoides Posterior",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Inclinado hacia adelante, eleva mancuernas hacia los lados focalizando deltoides posterior.",
        tempo: "2 - 1 - 1 - 0",
        category: "shoulders",
        difficulty: "Intermedio",
        image: getImg("reverse_fly"),
      },
      {
        id: "d11-db-10",
        name: "Curl de Bíceps Clásico",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Flexión de codos con supinación. Mantén los codos pegados al torso.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Intermedio",
        image: getImg("dumbbell_biceps"),
      },
      {
        id: "d11-db-11",
        name: "Curl Martillo",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Agarre neutro (palmas enfrentadas) para incidir en el braquial y antebrazo.",
        tempo: "2 - 0 - 2 - 0",
        category: "biceps",
        difficulty: "Intermedio",
        image: getImg("hammer_curl"),
      },
      {
        id: "d11-db-12",
        name: "Extensión de Tríceps sobre Cabeza",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Extensión vertical de tríceps. Codos cerrados apuntando al techo.",
        tempo: "2 - 1 - 1 - 0",
        category: "triceps",
        difficulty: "Intermedio",
        image: getImg("overhead_extension"),
      },
      {
        id: "d11-db-13",
        name: "Patada de Tríceps",
        sets: 3,
        reps: "12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Torso inclinado, extiende el codo hacia atrás apretando el tríceps arriba.",
        tempo: "2 - 1 - 1 - 0",
        category: "triceps",
        difficulty: "Intermedio",
        image: getImg("triceps_kickback"),
      },
      {
        id: "d11-db-14",
        name: "Sentadilla Goblet",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Mancuerna pegada al pecho, desciende profundo con el torso vertical y rodillas hacia fuera.",
        tempo: "3 - 1 - 1 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("goblet_squat"),
      },
      {
        id: "d11-db-15",
        name: "Sentadilla Búlgara con Mancuernas",
        sets: 3,
        reps: "10 por pierna",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Pie trasero elevado en banco, desciende con control focalizando cuádriceps y glúteo.",
        tempo: "2 - 1 - 1 - 0",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("bulgarian_split"),
      },
      {
        id: "d11-db-16",
        name: "Zancadas con Mancuernas",
        sets: 3,
        reps: "10 por pierna",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Pasos controlados con mancuernas a los lados manteniendo el torso erguido.",
        tempo: "2 - 0 - 1 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("walking_lunges"),
      },
      {
        id: "d11-db-17",
        name: "Hip Thrust con Mancuerna",
        sets: 3,
        reps: "12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Espalda alta en banco y mancuerna en la pelvis. Extensión completa de cadera con bloqueo arriba.",
        tempo: "2 - 2 - 1 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("dumbbell_glute"),
      },
      {
        id: "d11-db-18",
        name: "Subidas a Cajón con Mancuernas",
        sets: 3,
        reps: "10 por pierna",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Sube al banco empujando fuerte con la pierna de apoyo sin impulsarte con la trasera.",
        tempo: "2 - 0 - 1 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("dumbbell_step_up"),
      },
      {
        id: "d11-db-19",
        name: "Dumbbell Thrusters",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Sentadilla frontal encadenada en un solo movimiento explosivo con press de hombros.",
        tempo: "2 - 0 - 1 - 0",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("dumbbell_thrusters"),
      },
      {
        id: "d11-db-20",
        name: "Devil Press con Mancuernas",
        sets: 3,
        reps: "8-10",
        restSeconds: 75,
        equipment: "dumbbells",
        description:
          "Burpee apoyado sobre mancuernas seguido de balanceo explosivo a press sobre cabeza.",
        tempo: "Explosivo",
        category: "full_body",
        difficulty: "Avanzado",
        image: getImg("devil_press"),
      },
    ],
    alternativeExercises: [
      {
        id: "d11-bw-1",
        name: "Flexiones Clásicas",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Flexiones en suelo con pecho rozando el suelo y núcleo completamente compacto.",
        tempo: "2 - 0 - 1 - 0",
        category: "chest",
        difficulty: "Principiante",
        image: getImg("classic_push_ups"),
      },
      {
        id: "d11-bw-2",
        name: "Flexiones Explosivas",
        sets: 3,
        reps: "10",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Empuje con máxima aceleración concéntrica para desarrollar potencia pectoral.",
        tempo: "Explosivo",
        category: "chest",
        difficulty: "Avanzado",
        image: getImg("classic_push_ups"),
      },
      {
        id: "d11-bw-3",
        name: "Flexiones Inclinadas en Banco",
        sets: 3,
        reps: "15",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Manos apoyadas en banco o pared para mayor volumen y congestión pectoral.",
        tempo: "2 - 0 - 2 - 0",
        category: "chest",
        difficulty: "Principiante",
        image: getImg("wall_bench_push"),
      },
      {
        id: "d11-bw-4",
        name: "Fondos en Banco para Tríceps",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Manos al borde del banco y piernas extendidas, flexiona codos a 90 grados y empuja.",
        tempo: "2 - 1 - 1 - 0",
        category: "triceps",
        difficulty: "Intermedio",
        image: getImg("wall_bench_push"),
      },
      {
        id: "d11-bw-5",
        name: "Sentadillas Libres",
        sets: 3,
        reps: "20",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Sentadillas de peso corporal profundas manteniendo espalda recta y ritmo constante.",
        tempo: "2 - 0 - 1 - 0",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("bodyweight_squats"),
      },
      {
        id: "d11-bw-6",
        name: "Sentadillas con Salto",
        sets: 3,
        reps: "15",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Sentadilla profunda terminando con salto vertical explosivo y recepción suave.",
        tempo: "Explosivo",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("jump_squats"),
      },
      {
        id: "d11-bw-7",
        name: "Zancadas Caminando",
        sets: 3,
        reps: "12 por pierna",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Zancadas dinámicas avanzando con paso firme, rodilla trasera rozando el suelo.",
        tempo: "2 - 0 - 1 - 0",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("walking_lunges"),
      },
      {
        id: "d11-bw-8",
        name: "Zancadas con Salto",
        sets: 3,
        reps: "10 por pierna",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Zancadas alternadas en el aire con potencia pliométrica de piernas.",
        tempo: "Explosivo",
        category: "legs",
        difficulty: "Avanzado",
        image: getImg("jumping_lunges"),
      },
      {
        id: "d11-bw-9",
        name: "Wall Sit Isométrico",
        sets: 3,
        reps: "45s",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Espalda apoyada en la pared con rodillas flexionadas a 90 grados. Trabajo estático.",
        tempo: "Estático",
        category: "legs",
        difficulty: "Intermedio",
        image: getImg("wall_sit"),
      },
      {
        id: "d11-bw-10",
        name: "Puente de Glúteo en Suelo",
        sets: 3,
        reps: "15-20",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Tumbado boca arriba, eleva la pelvis contrayendo glúteos al máximo arriba durante 1 segundo.",
        tempo: "2 - 1 - 1 - 0",
        category: "legs",
        difficulty: "Principiante",
        image: getImg("dumbbell_glute"),
      },
      {
        id: "d11-bw-11",
        name: "Burpees Clásicos",
        sets: 3,
        reps: "10-12",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Cuerpo a tierra completo, recogida rápida de pies y salto con palmada sobre cabeza.",
        tempo: "Fluido",
        category: "full_body",
        difficulty: "Intermedio",
        image: getImg("burpees"),
      },
      {
        id: "d11-bw-12",
        name: "Mountain Climbers",
        sets: 3,
        reps: "40s",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "En plancha alta, lleva rodillas al pecho alternadamente a máxima velocidad.",
        tempo: "Rápido",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("mountain_climbers"),
      },
      {
        id: "d11-bw-13",
        name: "Plank Jacks en Suelo",
        sets: 3,
        reps: "40s",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Desde posición de plancha, abre y cierra pies de forma dinámica sin subir la cadera.",
        tempo: "Rápido",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("plank_jack"),
      },
      {
        id: "d11-bw-14",
        name: "Plancha Isométrica de Antebrazos",
        sets: 3,
        reps: "45s",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Apoyo sobre antebrazos, cuerpo alineado de cabeza a talones con abdomen y glúteos tensos.",
        tempo: "Estático",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("plank_single"),
      },
      {
        id: "d11-bw-15",
        name: "Elevaciones de Piernas para Abdomen",
        sets: 3,
        reps: "12-15",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Tumbado boca arriba, sube las piernas juntas a 90 grados y baja despacio sin tocar el suelo.",
        tempo: "3 - 0 - 1 - 0",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("leg_raise"),
      },
      {
        id: "d11-bw-16",
        name: "Abdominales Bicicleta / Crunch",
        sets: 3,
        reps: "20 totales",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Lleva el codo hacia la rodilla contraria alternando giros con contracción oblicua.",
        tempo: "2 - 1 - 2 - 0",
        category: "core",
        difficulty: "Intermedio",
        image: getImg("abdominal_crunch"),
      },
      {
        id: "d11-bw-17",
        name: "Jumping Jacks",
        sets: 3,
        reps: "45s",
        restSeconds: 30,
        equipment: "bodyweight",
        description:
          "Saltos coordinados abriendo piernas y brazos para elevar pulsaciones y quemar grasa.",
        tempo: "Continuo",
        category: "full_body",
        difficulty: "Principiante",
        image: getImg("jumping_jacks"),
      },
      {
        id: "d11-bw-18",
        name: "High Knees",
        sets: 3,
        reps: "30s",
        restSeconds: 75,
        equipment: "bodyweight",
        description:
          "Carrera en el sitio elevando rodillas a la altura de la cintura con braceo potente.",
        tempo: "Máxima velocidad",
        category: "full_body",
        difficulty: "Intermedio",
        image: getImg("high_knees"),
      },
      {
        id: "d11-bw-19",
        name: "Rotaciones Articulares Dinámicas",
        sets: 2,
        reps: "60s",
        restSeconds: 0,
        equipment: "bodyweight",
        description:
          "Movilidad global articular de hombros, cadera y columna para preparar el cuerpo.",
        tempo: "Fluido",
        category: "full_body",
        difficulty: "Principiante",
        image: getImg("joint_rotations"),
      },
    ],
  },
];

// Populate the global exercise catalog from all defined routines
routines.forEach((r) => {
  r.exercises.forEach(addExercise);
  r.alternativeExercises?.forEach(addExercise);
});

export const plans: Plan[] = [
  {
    id: "strength-3",
    name: "Fuerza 3 días",
    description:
      "Empuje, Tirón y el nuevo Full Body Combo. Equilibrio perfecto y máxima eficiencia.",
    daysPerWeek: 3,
    weeks: 4,
    schedule: [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
    tags: ["fuerza", "combo", "35-45 min"],
    recommended: true,
  },
  {
    id: "strength-4",
    name: "Fuerza 4 días",
    description:
      "Empuje, Tirón, Torso Power y Pierna & Glúteo. Mayor volumen y progresión muscular.",
    daysPerWeek: 4,
    weeks: 4,
    schedule: [1, 2, 5, 6, 1, 2, 5, 6, 1, 2, 5, 6, 1, 2, 5, 6],
    tags: ["fuerza", "hipertrofia", "35 min"],
    recommended: false,
  },
  {
    id: "hiit-2",
    name: "HIIT 2 días",
    description:
      "Dos sesiones de quema calórica extrema y mejora cardiovascular a la semana.",
    daysPerWeek: 2,
    weeks: 4,
    schedule: [4, 9, 4, 9, 4, 9, 4, 9],
    tags: ["cardio", "quema", "20-30 min"],
    recommended: false,
  },
  {
    id: "mixed",
    name: "Semana Completa Equilibrada",
    description:
      "Empuje, Tirón, HIIT, Full Body Combo y Movilidad. Rendimiento atlético integral.",
    daysPerWeek: 5,
    weeks: 4,
    schedule: [1, 2, 4, 3, 10, 1, 2, 4, 3, 10, 1, 2, 4, 3, 10, 1, 2, 4, 3, 10],
    tags: ["mixto", "completo", "20-45 min"],
    recommended: false,
  },
];

export const warmUpExercises = [
  {
    id: "wu-1",
    name: "Plancha Jack",
    sets: 1,
    reps: "30s",
    restSeconds: 75,
    equipment: "bodyweight" as const,
    description: "Core activado, pies abren y cierran sin mover los hombros.",
    image: getImg("plank_jack"),
  },
  {
    id: "wu-2",
    name: "Sentadillas libres",
    sets: 1,
    reps: "15",
    restSeconds: 75,
    equipment: "bodyweight" as const,
    description: "Calentamiento dinámico de tren inferior y apertura de cadera.",
    image: getImg("bodyweight_squats"),
  },
  {
    id: "wu-3",
    name: "Flexiones (pared/banco)",
    sets: 1,
    reps: "10",
    restSeconds: 75,
    equipment: "bodyweight" as const,
    description: "Activación suave de pecho, hombros y tríceps.",
    image: getImg("wall_bench_push"),
  },
  {
    id: "wu-4",
    name: "Jumping Jacks",
    sets: 1,
    reps: "30s",
    restSeconds: 75,
    equipment: "bodyweight" as const,
    description: "Elevación progresiva del ritmo cardíaco.",
    image: getImg("jumping_jacks"),
  },
  {
    id: "wu-5",
    name: "High Knees",
    sets: 1,
    reps: "30s",
    restSeconds: 30,
    equipment: "bodyweight" as const,
    description: "Activación de flexores de cadera y temperatura corporal.",
    image: getImg("high_knees"),
  },
  {
    id: "wu-6",
    name: "Elevación de Piernas",
    sets: 1,
    reps: "10",
    restSeconds: 30,
    equipment: "bodyweight" as const,
    description: "Activación del core profundo y zona lumbar.",
    image: getImg("leg_raise"),
  },
];
