import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // === v8 Titanium Volt Pro — athletic high-contrast palette ===
        background: "var(--background)",
        foreground: "var(--foreground)",
        surface: {
          950: "#0A0B10",
          900: "#111420",
          800: "#181C2C",
          700: "#22273C",
          600: "#2E354F",
          500: "#47506F",
          400: "#687499",
          300: "#909DC2",
          200: "#CBD5E1",
          100: "#F1F5F9",
          50: "#FFFFFF",
        },
        primary: {
          DEFAULT: "#D4FF00",
          container: "#D4FF00",
          fixed: "#D4FF00",
          "fixed-dim": "#A8CC00",
          600: "#BDE600",
          500: "#D4FF00",
          400: "#E0FF33",
          300: "#EBFF66",
          200: "#F2FF99",
          100: "#F9FFCC",
        },
        accent: {
          volt: "#D4FF00",
          cyan: "#00E5FF",
          flame: "#FF9500",
          rose: "#FF3B5C",
          violet: "#8B5CF6",
          amber: "#FFB800",
        },
        // === Legacy aliases (kept for gradual migration) ===
        "surface-container": {
          lowest: "#07080C",
          low: "#0E1018",
          DEFAULT: "#111420",
          high: "#181C2C",
          highest: "#22273C",
        },
        "on-primary": "#000000",
        "on-primary-container": "#000000",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#253000",
        secondary: {
          DEFAULT: "#CBD5E1",
          container: "#22273C",
        },
        "on-secondary": "#0A0B10",
        "on-secondary-container": "#CBD5E1",
        tertiary: {
          DEFAULT: "#F1F5F9",
          container: "#CBD5E1",
        },
        "on-tertiary": "#0A0B10",
        "on-tertiary-container": "#909DC2",
        "on-tertiary-fixed": "#0A0B10",
        "on-tertiary-fixed-variant": "#22273C",
        error: {
          DEFAULT: "#FF5370",
          container: "#93000A",
        },
        "on-error": "#FFFFFF",
        "on-error-container": "#FFDAD6",
        outline: {
          DEFAULT: "rgba(255,255,255,0.12)",
          variant: "rgba(255,255,255,0.07)",
        },
        "surface-tint": "#D4FF00",
        "on-surface": "#FFFFFF",
        "on-surface-variant": "#CBD5E1",
        "inverse-surface": "#F1F5F9",
        "inverse-on-surface": "#0A0B10",
        "inverse-primary": "#BDE600",
      },
      fontFamily: {
        display: ["var(--font-space-grotesk)", "var(--font-geist-sans)", "system-ui", "sans-serif"],
        sans: ["var(--font-inter)", "var(--font-geist-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
        // Legacy aliases
        montserrat: ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        inter: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      fontSize: {
        // v8 scale
        "display-xl": ["clamp(48px, 12vw, 80px)", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg": ["clamp(40px, 10vw, 64px)", { lineHeight: "1.05", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md": ["clamp(32px, 8vw, 48px)", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "title-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        // Legacy aliases
        "display-timer": ["clamp(56px, 15vw, 84px)", { lineHeight: "1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-timer-mobile": ["56px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-timer-tablet": ["64px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-timer-desktop": ["84px", { lineHeight: "84px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-xl-mobile": ["24px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-sm-mobile": ["16px", { lineHeight: "20px", fontWeight: "600" }],
      },
      spacing: {
        "touch-target-min": "48px",
        "container-padding": "20px",
        "stack-gap": "16px",
        "section-gap": "32px",
        base: "8px",
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        sm: "0.75rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "2rem",
      },
      maxWidth: {
        app: "600px",
      },
      boxShadow: {
        rest: "0 8px 30px rgba(0,0,0,0.7)",
        neon: "0 4px 20px rgba(212, 255, 0, 0.32)",
        "neon-strong": "0 6px 30px rgba(212, 255, 0, 0.48)",
        "cyan-neon": "0 4px 20px rgba(0, 229, 255, 0.32)",
        glow: "0 0 28px rgba(212, 255, 0, 0.35)",
        "glow-cyan": "0 0 28px rgba(0, 229, 255, 0.35)",
        "glow-flame": "0 0 28px rgba(255, 149, 0, 0.35)",
        "glow-violet": "0 0 28px rgba(139, 92, 246, 0.35)",
      },
      animation: {
        "pulse-a": "pulseA 2s infinite ease-in-out",
        "pulse-b": "pulseB 2s infinite ease-in-out",
        "fade-in-up": "fadeInUp 0.4s ease-out forwards",
        "pulse-slow": "pulseSlow 4s infinite ease-in-out",
        "gradient-x": "gradientX 3s ease infinite",
        "page-in": "pageIn 0.35s cubic-bezier(0.22, 1, 0.36, 1) forwards",
      },
      keyframes: {
        pulseA: {
          "0%, 100%": { opacity: "1", borderColor: "#00D68F", transform: "scale(1.02)" },
          "50%": { opacity: "0.4", borderColor: "#16222f", transform: "scale(1)" },
        },
        pulseB: {
          "0%, 100%": { opacity: "0.4", borderColor: "#16222f", transform: "scale(1)" },
          "50%": { opacity: "1", borderColor: "#00E1FF", transform: "scale(1.02)" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseSlow: {
          "0%, 100%": { opacity: "0.3", transform: "scale(1)" },
          "50%": { opacity: "0.6", transform: "scale(1.1)" },
        },
        gradientX: {
          "0%, 100%": { backgroundSize: "200% 200%", backgroundPosition: "left center" },
          "50%": { backgroundSize: "200% 200%", backgroundPosition: "right center" },
        },
        pageIn: {
          "0%": { opacity: "0", transform: "translateY(12px) scale(0.99)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
      },
      transitionTimingFunction: {
        "spring": "cubic-bezier(0.22, 1, 0.36, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
